### PR TITLE
Fixes some TES submissions issues

### LINKED ISSUE #1: Support additional endpoint binding
The additional endpoint bindings for tes are:

`/v1/tasks`
`/ga4gh/tes/v1/tasks`

### LINKED ISSUE #2: TES Tasks posts handle Null
When posting tes tasks. Tasks should not be Null, but rather should not be present when posting.

`{"id":null,"state":null,"name":null,"description":null,"inputs":null,"outputs":null,"resources":null,"executors":[{"image":"ubuntu:latest","command":["/bin/bash","-c","echo hello, world!"],"workdir":null,"stdin":null,"stdout":null,"stderr":null,"env":null}],"volumes":null,"tags":null,"logs":null,"creation_time":null}`

Should be
`{executors":[{"image":"ubuntu:latest","command":["/bin/bash","-c","echo hello, world!"]}`

### LINKED ISSUE #3: Basic Authentication error
For basic authentication should have rust deal with the encoding

### PR DESCRIPTION
**Pull request by vsmalladi**
Closes #1 
Closes #2 
Closes #3

### CODE REVIEW

File: src/v1/types/task.rs [hunk 1]
```diff
@@ -153,15 +164,19 @@ pub struct TaskLog {
...
     /// The start time.
+    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
     pub start_time: Option<DateTime<Utc>>,
 
     /// The end time.
+    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
     pub end_time: Option<DateTime<Utc>>,
 
     /// The output file logs.
+    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
```
Comment (claymcleod) [inline src/v1/types/task.rs]: This is a required key, so I'm going to remove this.

Comment (vsmalladi) [reply src/v1/types/task.rs]: good catch

File: src/v1/client.rs [hunk 2]
```diff
@@ -89,18 +89,11 @@ impl Client {
...
-            format!("{}/", self.url) // Append '/' if missing
-        };
-
         // SAFETY: as described in the documentation for this method, the URL is
-        // already validated upon creationg of the [`Client`], and the
+        // already validated upon creating of the [`Client`], and the
         // `endpoint` is assumed to always be joinable to that URL, so this
         // should always unwrap.
-        let url = Url::parse(&format!("{}{}", base_url, endpoint)).unwrap(); // Safely join the base URL and endpoint
+        let url = self.url.join(endpoint).unwrap();
```
Comment (claymcleod) [inline src/v1/client.rs:96]: I changed this back, and I'm not sure what it was actually doing—the `url::URL` does not include a trailing `/` when serialized (i.e., when printing to standard out), but all of that should be handled when the join method is used. Converting to string, appending the `/`, and then converting back to a `Url` seems to be accomplishing the same thing.

Let me know if I have misunderstood.

**Comment by claymcleod** [comment]
I also opened this as part of this investigation: https://github.com/ohsu-comp-bio/funnel/issues/1138.

**Comment by claymcleod** [comment]
@vsmalladi I think this should have you handled. Please give all of the examples a shot one more time to make sure I haven't re-broken anything.

File: src/v1/client.rs (hunk 2 above)
Comment (vsmalladi) [reply src/v1/client.rs:96]: @claymcleod sorry I think I wasn’t clear what the issue was. 

When I put the ‘url/v1’ as the endpoint the code only uses ‘url’ to make the api as ‘url/tasks’ path . so when I forced a backslash in the code then the path became  ‘url/v1/tasks’

Comment (claymcleod) [reply src/v1/client.rs:96]: Ah, I see what you mean now. Does the most recent commit sort this out for you? I think it's preferable because it only requires checking for the slash in one location.

Comment (vsmalladi) [reply src/v1/client.rs:96]: Looks great.

**Comment by vsmalladi** [comment]
@claymcleod  looks great. I think you can merge.
